platform :ios, '12.0'
workspace 'MediationExample.xcworkspace'

target 'SampleAdSDK' do
  project 'SampleAdSDK/SampleAdSDK.xcodeproj'
  pod 'Google-Mobile-Ads-SDK', '~> 12.9'

  target 'MediationExample' do
    project 'MediationExample.xcodeproj'
    inherit! :search_paths

    if ENV['BUILD_SNIPPETS']
      pod 'Snippets', :path => './Snippets'
    end

  end
end
