#!/bin/bash
#
# Clean up all the traces generated by `pod install`. When
# AdapterUnitTests.xcodeproj's dependencies are installed via Cocoapod, it adds
# pod-configurations to each of the adapter xcodeproj which the AdapterUnitTests
# depends on. This shell script completely removes the traces.

set -euo pipefail

# Make sure job will be executed from the correct directory.
cd "$(dirname "${BASH_SOURCE[0]}")"

# Clean up AdapterUnitTests directory.
pod deintegrate
if [ -f ./Podfile.lock ]; then
  rm ./Podfile.lock
fi
if [ -d ./AdapterUnitTests.xcworkspace ]; then
  rm -r ./AdapterUnitTests.xcworkspace
fi

# Clean up pod configurations from all the adapter projects.
for adapter_xcodeproj_location in $(find ../adapters -name '*.xcodeproj'); do
  adapter_xcodeproj_dir=$(dirname "$adapter_xcodeproj_location")
  cd "$adapter_xcodeproj_dir"
  pod deintegrate
  cd -
done
