# To download all the dependencies:
# pod install
#
# To download adapters selectively:
# ADAPTER_TARGETS="TargetName1,TargetName2"

platform :ios, '11.0'

adapter_targets = ENV['ADAPTER_TARGETS']&.split(',') || []

abstract_target 'Default' do

  pod 'Google-Mobile-Ads-SDK', "~> 10.0"

  target 'AdapterUnitTestKit' do
  end

end
